openshift/cluster-api-provider-aws

README.md

Once building the images in automated way we will need to either install the upstream docker and replace the `docker build` with `imagebuilder`.

Mention the docker build does not work with RH docker, imagebuilder as its replacement

---

README.md
examples/addons.yaml
examples/cluster-api-server.yaml
examples/machine-set.yaml
examples/machine.yaml
examples/provider-components.yml

The examples are still specific for resources assigned to `tb-asg-35` vpc. Yet, anyone with the proper aws credentials can reuse them.

Describe how to deploy the cluster-api stack with minikuber + KVM

---

Makefile

It takes a lot of time to sync the vendor dir that it's better to do it on request only.

Do not dep ensure anything

---

examples/cluster-api-server.yaml

Fixes:
```console
Error from server (NotFound): error when
creating "examples/cluster-api-server.yaml":
the server could not find the requested resource.```

examples/cluster-api-server: add missing version in RoleBinding

---

cloud/aws/actuators/machine/utils.go

Provider status was being written the first time with APIVersion of
cluster.k8s.io which is not correct for the AWSMachineProviderStatus.
This would then fail to decode on all subsequent attempts to update
status.
This patch fixes but the apiVersion is now awsproviderconfig/v1alpha1,
which should also probably be fixed in a follow-up. https://github.com/openshift/cluster-api-provider-aws/issues/18
Worth noting the error appeared to get swallowed and never logged,
which also should be fixed in a follow-up. https://github.com/openshift/cluster-api-provider-aws/issues/17

Fix machine status updates due to wrong APIVersion.

---

README.md
examples/render-aws-secrets.sh

Convenience script to render AWS secrets:
$ cd $GOPATH/sigs.k8s.io/cluster-api-provider-aws
$ ./examples/update-aws-secrets.sh examples/addons.yaml
```yaml
apiVersion: v1
kind: Namespace
metadata:
name: test
---
apiVersion: v1
kind: Secret
metadata:
name: aws-credentials-secret
namespace: test
type: Opaque
data:
awsAccessKeyId: <REDACTED>
awsSecretAccessKey: <REDACTED>
```
Normal usage would be:
$ ./examples/render-aws-secrets.sh examples/addons.yaml | kubectl apply -f -
Only works if both:
- AWS_SECRET_ACCESS_KEY
- AWS_ACCESS_KEY_ID
are set in the environment.

Add convenience script to update AWS secrets

---

Makefile
cmd/aws-actuator/main.go
examples/worker-machine.yaml

Just run `./bin/aws-actuator bootstrap --manifests examples/` and get:
```
$ sudo kubectl get nodes
NAME                            STATUS    ROLES     AGE       VERSION
ip-172-31-33-59.ec2.internal    Ready     master    1m        v1.11.2
ip-172-31-35-115.ec2.internal   Ready     <none>    52s       v1.11.2
```

New 'aws-actuator bootstrap` command to bootstrap the kubernetes cluster from scratch

---

cmd/aws-actuator/main.go

So it's easier to find who created the AWS instances.
@frobware @enxebre

Prefix machines when bootstrapping

---

cloud/aws/actuators/machine/actuator.go
examples/machine-with-filters.yaml

This allows to integrate the openshift actuator with mao and the installer:
- https://github.com/enxebre/installer/blob/mao/modules/bootkube/resources/manifests/mao-config.yaml#L3
- https://github.com/openshift/machine-api-operator/pull/34

add support for filters on sg and subnet

---

Dockerfile
cmd/machine-controller/Makefile

Move Dockerfile to project root to accomodate tooling, needs to have
source in build context.
Make sure GOPATH is set, it may not be in some build images that get
auto-replaced in for the FROM.
Workaround a bug in some versions of imagebuilder where WORKDIR will not
create the directory if it doesn't exist.
We can't yet test this but I spoke with lmeyer and he spotted a couple things that might be needed, so submitting a PR for those. Let me know if anything else needs to be updated, I may have missed other routes to the Dockerfile I'm not aware of.
CC @enxebre @paulfantom

Prep Dockerfile for building with ART tooling.

---

Makefile
hack/go-fmt.sh
hack/go-lint.sh
hack/go-vet.sh

use origin-release images for tooling

---

cmd/aws-actuator/main.go

So it's clear which kubeconfig to take. Not `~/.kube/config` neither the one set through `KUBECONFIG`.

Run kubectl with explicit kubeconfig

---

cmd/aws-actuator/README.md
cmd/aws-actuator/main.go
examples/worker-machineset.yaml

- provision one master node with the aws actuator
- deploy the cluster API stack inside the master node
- provision additional worker node via the cluster API (through machineset)
In case more worker machinesets are needed, one can create new machineset based on the default one and just reuse the user data credentials with script allowing to install and join new node via `kubeadm`.

Deploy worker machines via machineset

---

examples/worker-machineset.yaml

Once needs to run `nodelink-controller` controller to properly label the nodes:
```
./bin/nodelink-controller --kubeconfig=KUBECONFIG
```
The functionality will be available once https://github.com/openshift/machine-api-operator/pull/72 gets merged. Not blocker for this PR however.

Annotate workers with node role

---

hack/aws-provision.sh

Previously you had to `cd hack` before running `aws-provision.sh`.
This commit allows you to invoke it from anywhere.

hack/aws-provision.sh: make it runnable from any directory

---

Makefile
examples/provider-components.yml
test/framework/clusterapi.go
test/framework/clusters.go
test/framework/framework.go
test/framework/machines.go
test/machines/awsclient.go
test/machines/machines_test.go
test/uploadDockerImages.sh
test/utils/manifests.go

- Deploy the nodelink-controller with deploying the cluster API stack.
- Recreate the cluster API stack in random namespaces before a spec is run.
- Testing for nore roles and machine-node matching requires a new cluster to be deployed via the cluster API. Thus, locally build aws actuator image needs to be uploaded to newly provisioned master node.
- Put semantically closed operations into methods/functions so they can be reused in specs.
- Scale down before deleting deployments/statefulset. It can take some time before the deployments/statefullset is actually deleted. New cluster API stack can be deployed even though there are already existing deployments from any previous run as long as there is zero replicas of previously  created pods.
- Some of the code is still aws actuator …

E2E: verify node roles and node machine matching

---

hack/aws-provision.sh
hack/prebuild/main.tf

E.g. to clean all resources created during CI run. It can happen a Jenkin jobs is aborted or fails and does not clean all running instances created during testing.

Terminate instances before destroying vpc

---

Makefile

Invoking:
$ make build DBG=1
or
$ make aws-actuator DBG=1
will build cmd/cluster-controller, cmd/machine-controller and
bin/aws-actuator with Go debug support. The build rules for those
three binaries are now `go build $(GOGCFLAGS) ...`.
The default value for GOGCFLAGS is -gcflags=all="-N -l", assuming
GOGCFLAGS it not already set in your environment. "all" specifies that
the flags should be applied to all packages (and may rebuild existing
up to date packages); "-N" disables compiler optimisations and "-l"
prevents inlining.
So, to override the defaults:
$ make build DBG=1 GOGCFLAGS='-gcflags="-N -l"'

Makefile: add Go debug support for local binaries

---

pkg/cloud/aws/actuators/machine/actuator.go

unify how we get the clusterid to use the machine label so we don't rely on the cluster object at all

unify clusterid retrieval

---

pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine/actuator_test.go

related to: https://github.com/openshift/installer/pull/468#issuecomment-430050471

Drop duplicate instance tags, if exists

---

0001-Delete-annotated-machines-first-when-scaling-down.patch
0002-Sort-machines-before-syncing.patch
vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go

Update and apply the scale down patches

update and run scale down patches

---

pkg/apis/awsproviderconfig/v1alpha1/awsmachineproviderconfig_types.go
pkg/apis/awsproviderconfig/v1alpha1/zz_generated.deepcopy.go
pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine/actuator_test.go

Introduces the capability of adding machines to specified Load Balancers as they are created or updated.
The LoadBalancer field in ProviderConfig is renamed from LoadBalancerIDs to LoadBalancerNames and its type set to string. AWS only allows specifying load balancers by name, and their describe call doesn't allow Filters.
Depends on https://github.com/openshift/cluster-api-provider-aws/pull/81

Load Balancer update

---

pkg/cloud/aws/actuators/machine/actuator.go

Because logs like:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/525/pull-ci-openshift-installer-master-e2e-aws/867/artifacts/e2e-aws/pods/openshift-cluster-api_clusterapi-manager-controllers-76c6686888-brwk4_aws-machine-controller.log.gz | gunzip  | tail -n 11
time="2018-10-24T15:08:11Z" level=debug msg="finished calculating AWS status" controller=awsMachine instanceID=i-0d6c4a1b08ea79f9e machine=openshift-cluster-api/ci-op-kgknj8yp-1d3f3-worker-0-sjvd8
time="2018-10-24T15:08:11Z" level=info msg="machine status has changed, updating" controller=awsMachine instanceID=i-0d6c4a1b08ea79f9e machine=openshift-cluster-api/ci-op-kgknj8yp-1d3f3-worker-0-sjvd8
time="2018-10-24T15:08:12Z" level=debug msg="checking if machine exists" …
```

updateMachineStatus: Log changes with ObjectReflectDiff

---

Makefile

`test-e2e` target should have the same meaning in all cloud team repositories and implement an e2e gating job against OpenShift cluster.
Relates to https://github.com/openshift/cluster-api-provider-aws/pull/113#discussion_r237463463

rename test-e2e to unify this target meaning along all repos

---

cmd/aws-actuator/main.go
pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine/actuator_test.go
test/integration/create_update_delete_test.go

The golang.org/x/net/context.Context is just an alias for context.Context.
Unless necessary let's stick with the definition from the stdlib.
See https://github.com/golang/net/blob/351d144fa1fc0bd934e2408202be0c29f25e35a0/context/go19.go#L15

Import right context package

---

cmd/aws-actuator/main.go
cmd/manager/main.go
pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine/actuator_test.go

Record important error messages as events so they can be reported when describing a machine object.

Record machine events

---

config/crds/machineset.crd.yaml

This adds 'desired', 'current' and 'ready' replica counts as default
columns for `kubectl get machinesets`. It also adds 'age'. This output
mirrors the output you get from `kubectl get replicasets`.

crd/machinesets: add additional printer columns

---

pkg/cloud/aws/actuators/machine/actuator_test.go
pkg/cloud/aws/actuators/machine/awsclient_test.go
pkg/cloud/aws/actuators/machine/instaces_test.go
pkg/cloud/aws/actuators/machine/loadbalancers_test.go
pkg/cloud/aws/actuators/machine/stubs.go
pkg/cloud/aws/actuators/machine/utils.go

Increase unit test coverage before:
- sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/machine/actuator.go (62.1%)
- sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/machine/awsclient.go (0.0%)
- sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/machine/instances.go (52.9%)
- sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/machine/loadbalancers.go (18.4%)
- sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/machine/utils.go (53.9%)
Increase unit test coverage after:
- sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/machine/actuator.go (91.6%)
- sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/machine/awsclient.go (100.0%)
- sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/machine/instances.go …

Increase unit test coverage of pkg/cloud/aws/actuators/machine

---

cmd/aws-actuator/main.go
cmd/aws-actuator/utils/utils.go
cmd/manager/main.go
pkg/cloud/aws/actuators/machine/actuator.go
pkg/cloud/aws/actuators/machine/actuator_test.go
pkg/cloud/aws/client/client.go
test/integration/create_update_delete_test.go
test/machines/machines_test.go

Built on top of https://github.com/openshift/cluster-api-provider-aws/pull/127
This is the last occurrence where we use Kubernetes client (besides e2e framework).

Remove kubeclient in favor of runtime controller client

---

Makefile

During renaming of validate-e2e to test-e2e we forget
to rename the label itself. Thus, the test-e2e was not
doing anything at all.

Fix make test-e2e

---

Gopkg.lock
cmd/manager/main.go
pkg/actuators/machine/actuator.go
pkg/actuators/machine/actuator_test.go
test/e2e/main.go
test/e2e/provider_expectations.go
vendor/github.com/go-log/log/LICENSE
vendor/github.com/go-log/log/README.md
vendor/github.com/go-log/log/capture/capture.go
vendor/github.com/go-log/log/fmt/fmt.go
vendor/github.com/go-log/log/info/info.go
vendor/github.com/go-log/log/log.go
vendor/github.com/go-log/log/log/log.go
vendor/github.com/go-log/log/nest/nest.go
vendor/github.com/go-log/log/print/print.go
vendor/github.com/openshift/kubernetes-drain/LICENSE
vendor/github.com/openshift/kubernetes-drain/drain.go

- drain nodes before deletion only if `drain-node: True` annotation is present on machine object)
- integrate the logic into the aws actuator Delete operation directly (until the node drain library is actually merged in k8s itself)
Continuing with work provided in https://github.com/openshift/cluster-api-provider-aws/pull/60

[RFE] Drain nodes before deletion if requested

---

cmd/aws-actuator/main.go
config/crds/cluster.crd.yaml
config/crds/machine.crd.yaml
config/crds/machinedeployment.crd.yaml
config/crds/machineset.crd.yaml
examples/machine-set.yaml
examples/machine-with-filters.yaml
examples/machine-with-user-data.yaml
examples/machine.yaml
examples/master-machine.yaml
examples/worker-machine.yaml
examples/worker-machineset.yaml
pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/stubs.go
pkg/actuators/machine/utils.go
pkg/actuators/machine/utils_test.go
pkg/apis/awsproviderconfig/v1alpha1/register.go
pkg/apis/awsproviderconfig/v1alpha1/register_test.go
test/machines/machines_test.go
test/utils/manifests.go
vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go

- remove any use of the `.providerConfig` and `ProviderConfig`
- rename testing resources to reflect new provider spec name
- rename [Encode|Decode]ProviderConfig to [Encode|Decode]ProviderSpec
/hold
until freeze is over and https://github.com/openshift/machine-api-operator/pull/170 is merged

Remove providerconfig

---

0001-Delete-annotated-machines-first-when-scaling-down.patch
vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/delete_policy.go

The latest cluster-api has changed the machine deletion policy.
Updating the downstream patch accordingaly to it.

Update delete policy downstream patch and re-apply it

---

0001-Validate-machineset-before-reconciliation.patch
Makefile
vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go

Even thought the MachineSet type implements Validate() function,
it's not called by default. The validation function is responsible
for making sure every machine set matchLabels selector is matched with
machine template labels. Given the validation is not performed by default,
it is possible to create an invalid machineset that causes the machineset
controller to start creating machine object one by one without any upper
bound. Causing the machine controller to launch as many instances as
there is machine objects.
Carried as downstream patch before https://github.com/kubernetes-sigs/cluster-api/pull/669 gets resolved.

Validate machineset before reconciling

---

0001-Upstream-677-Init-klog-in-manager-properly.patch
Makefile
cmd/manager/main.go
vendor/sigs.k8s.io/cluster-api/cmd/manager/main.go

Resolving https://github.com/kubernetes-sigs/cluster-api/issues/607 for
machine controller and controller manager.
Until glog is migrated to klog, the klog flags need to be
synchronized with glog ones. Otherwise, glog shadows klog flags.
Upstream issue: https://github.com/kubernetes-sigs/cluster-api/pull/677

Initialize klog alongside with glog

---

Makefile
pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/instaces_test.go
pkg/actuators/machine/instances.go
pkg/client/client.go
pkg/client/fake/fake.go
pkg/client/mock/client_generated.go

Improve user experience by logging availability zone does not exist instead of logging subnet not found if availability zone does not exist.
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1664595

Log if availability zone does not exist

---

pkg/actuators/machine/instances.go

We currently don't apply name tag to the EBS volume, hence it shows empty on the aws console.
This consolidate tags applied to machines and their corresponding volume

Apply tagList to the ebs volume

---

test/e2e/main.go
test/e2e/provider_expectations.go

Update e2e test to run against machine.openshift.io
Needs https://github.com/openshift/installer/pull/1175

Update e2e test to run against machine.openshift.io

---

Makefile
pkg/actuators/machine/actuator.go
pkg/actuators/machine/stubs.go
test/e2e/provider_expectations.go
test/machines/machines_test.go

So far a node was drained only when requested. From now on a node is drained by default unless "machine.openshift.io/exclude-node-draining" annotation key is specified. At the same time if a node draining is requested but a machine has no node reference, machine deletion is rejected.

Drain nodes by default unless explicitly set to exclude

---

test/e2e/main.go
test/e2e/provider_expectations.go

Since this [openshift/installer@37b25ea#diff-a25ec653fe393c89c4ccac5a1edfe38fL51](https://github.com/openshift/installer/commit/37b25ea64964ad0671e6f498b57646efe641ad6f#diff-a25ec653fe393c89c4ccac5a1edfe38fL51) got in the cluster obejct needs to exist however is circumstantial for the actuator and no need to validate it exist or not here. See https://jira.coreos.com/browse/CLOUD-357
https://github.com/openshift/machine-api-operator/pull/216

Drop cluster test since it's not relevant for the actuator

---

pkg/actuators/machine/actuator.go
test/e2e/main.go
test/e2e/provider_expectations.go

New test for node draining (respecting PDB)

---

examples/machine-set.yaml
examples/machine-with-filters.yaml
examples/machine-with-user-data.yaml
examples/machine.yaml
examples/master-machine.yaml
examples/worker-machine.yaml
examples/worker-machineset.yaml
pkg/actuators/machine/actuator.go
pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go
test/e2e/provider_expectations.go

Rename labels from sigs.k8s.io to machine.openshift.io

---

pkg/client/client.go

This should help identify requests made my cluster-api-provider-aws.
Ques: how to get version information.

client: add cluster-api-provider-aws to UserAgent for AWS API calls

---

pkg/apis/awsproviderconfig/v1beta1/register.go

`awsproviderconfig.k8s.io/v1alpha1` API version changed to `awsproviderconfig.openshift.io/v1beta1` [1]. We can switch back to codec decoding.
[1] https://github.com/openshift/installer/pull/1223

Drop the yaml unmarshalling

---

vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go

When deleting a machine this also deletes the backed node right away from the machine controller after the actuator succeed deleting the cloud instance, so no need to wait for the cloud nodelifecycle controller to garbage collect the orphan node
related https://github.com/openshift/origin/pull/22090
Counter part PR https://github.com/openshift/cluster-api/pull/12

Delete node after removing cloud instance on deletion

---

pkg/actuators/machine/actuator.go
pkg/actuators/machine/stubs.go
test/machines/machines_test.go
vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go

Node draining is a generic operation independent of a specific actuator.
Thus, it makes sense to move the code from actuator into the machine controllers.
The node draining code itself is imported from github.com/openshift/kubernetes-drain.
At the same time it's currently impossible to use the controller-runtime client for node draining
due to missing Patch operation (https://github.com/kubernetes-sigs/controller-runtime/pull/235).
Thus, the machine controller needs to initialize kubeclient as well in order to
implement the node draining logic. Once the Patch operation is implemented,
the draining logic can be updated to replace kube client with controller runtime client.
Also, initialize event recorder to generate node draining event.
Corresponding openshift upstream PR here: …

Move node draining from actuator into machine controller

---

.gitignore
cmd/aws-actuator/main.go
cmd/manager/main.go
pkg/actuators/machine/actuator.go
pkg/actuators/machine/instances.go
pkg/actuators/machine/loadbalancers.go
pkg/actuators/machine/utils.go

Based on https://github.com/openshift/machine-api-operator/pull/231
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
- if an error message is just printed, use uppercase
- if an error message is return by a function/method and passed on, use lowercase
- NOUN VERB STATE format when possible
/assign @ingvagabund

Consistent log messages

---

pkg/actuators/machine/actuator.go
vendor/github.com/openshift/cluster-api/pkg/apis/machine/common/consts.go
vendor/github.com/openshift/cluster-api/pkg/errors/machines.go

In case a load balancer were not updated.
Or, to report a machine configuration is invalid.
Reporting successful machine update operation will also
drops the invalid machine configuration event.
Corresponding openshift cluster-api PR: https://github.com/openshift/cluster-api/pull/14

Record update events as well

---

cmd/manager/main.go

Currently resync is set to 10 hours https://github.com/kubernetes-sigs/cluster-api/blob/master/vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go#L88 which makes external provider state changes almost ignored by the controller. This PR makes reconciling to happen more frequently
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/671

Reduce resync period from 10 hours to 10 minutes

---

pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go

IOPS constrained for individual volumes may vary over time.
Rather, direct a reader to the AWS documentation instead of
explicitly stating the boundaries.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1691208

Do not be explicit about iops constraints

---

examples/machine-set.yaml
examples/machine-with-filters.yaml
examples/machine-with-user-data.yaml
examples/machine.yaml
examples/master-machine.yaml
pkg/actuators/machine/actuator.go
pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/stubs.go
pkg/actuators/machine/utils.go
pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go

https://jira.coreos.com/browse/CLOUD-407

Drop unused labels from installer machineSets

---

hack/go-fmt.sh
hack/go-vet.sh

Running `make vet` yields:
```console
$ make vet
hack/go-vet.sh ./...
cmd/aws-actuator/main.go:45:2: cannot find package "sigs.k8s.io/cluster-api-provider-aws/pkg/actuators/machine" in any of:
/go/src/github.com/openshift/cluster-api-provider-aws/vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/actuators/machine (vendor tree)
/usr/local/go/src/sigs.k8s.io/cluster-api-provider-aws/pkg/actuators/machine (from $GOROOT)
/go/src/sigs.k8s.io/cluster-api-provider-aws/pkg/actuators/machine (from $GOPATH)
cmd/aws-actuator/utils.go:22:2: cannot find package "sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1beta1" in any of:
/go/src/github.com/openshift/cluster-api-provider-aws/vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsproviderconfig/v1beta1 (vendor tree) …
```

fix source paths when invoking vet and fmt scripts

---

Dockerfile
Dockerfile.rhel7
Gopkg.lock
Makefile
cmd/manager/main.go
pkg/client/client.go
pkg/version/version.go
vendor/github.com/blang/semver/.gx/lastpubver
vendor/github.com/blang/semver/.travis.yml
vendor/github.com/blang/semver/LICENSE
vendor/github.com/blang/semver/README.md
vendor/github.com/blang/semver/examples/main.go
vendor/github.com/blang/semver/json.go
vendor/github.com/blang/semver/package.json
vendor/github.com/blang/semver/range.go
vendor/github.com/blang/semver/semver.go
vendor/github.com/blang/semver/sort.go
vendor/github.com/blang/semver/sql.go

Introduce `version` support for user agents and CLI retrieval trough `-version` flag.
Version gets set during building process of AWS actuator.

Version support

---

hack/prebuild/main.tf

```
31mError downloading modules: Error loading modules: module vpc: Error parsing .terraform/modules/2b0dfe72e06da71d934d6da6693d5852/terraform-aws-modules-terraform-aws-vpc-e99089a/main.tf: At 2:23: Unknown token: 2:23 IDENT max[0m[0m
```
And because of this error in `terraform init` subnet is not getting created which results in machine creation failure:
```
E0531 11:44:08.153778       1 actuator.go:104] Machine error: error launching instance: error getting subnet IDs: no subnet IDs were found,
E0531 11:44:08.153804       1 actuator.go:113] error creating machine: error launching instance: error getting subnet IDs: no subnet IDs were found,
```
Related: https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/267#issuecomment-495858008

Fix CI/jenkins e2e env setup

---

pkg/actuators/machine/actuator.go
pkg/actuators/machine/utils.go

Currently, any non-existing instance is recreated during machine reconciliation.
In case an AWS instance is stopped for maintenance purposes, it is considered
as it would be terminated. Which is not the expected behaviour.
Instead, consider such instance to be existing until its status changes back to
running or is terminated.

Stopped instances existing

---

pkg/actuators/machine/actuator.go
pkg/actuators/machine/utils.go

Currently, any non-existing instance is recreated during machine reconciliation.
In case an AWS instance is stopped for maintenance purposes, it is considered
as it would be terminated. Which is not the expected behaviour.
Instead, consider such instance to be existing until its status changes back to
running or is terminated.
Side effect: stopped worker machines will not get reconciled.

Consider non-terminated instances to be existing

---

Gopkg.lock
vendor/github.com/openshift/cluster-api/Gopkg.lock
vendor/github.com/openshift/kubernetes-drain/drain.go

This commit fixes a bug where drain does not wait for
completion of eviction or deletion of pods due to
missing namespace attribute when checking if pod still
exists after drain operation.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1729512

Update vendor cluster-api and kubernetes-drain

---

Gopkg.lock
vendor/github.com/openshift/kubernetes-drain/drain.go

This commit fixes a bug where drain does not wait for
completion of eviction or deletion of pods due to
missing namespace attribute when checking if pod still
exists after drain operation.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1729243
Backports: 394c11e22a3474453d05a3227f40540f2d76c9c6
Backports: https://github.com/openshift/cluster-api-provider-aws/pull/237

Bug 1729243: Update vendor kubernetes-drain

---

pkg/actuators/machine/instances.go

AWS actuator allows to specify encrypted root volumes for compute machines.
Though, it does not wire it to EBS definition which is passed to AWS ec2 service.
The provider should respect the setting and provision encrypted volumes when requested.
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1734193

Bug 1734193: Wire provider spec EBS volume Encrypted field into ec2.EbsBlockDevice.Encrypted field

---

Gopkg.lock
pkg/actuators/machine/actuator.go
pkg/actuators/machine/instances.go
pkg/actuators/machine/utils.go
vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machine.yaml
vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machineset.yaml
vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machineset_types.go
vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/sync.go
vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go

Set common machine fields so when a machine provisioned in AWS is listed through `oc get machines`
all additional printer colums are properly populated. E.g. region, zone, instance type.
During the provisioning stage:
```
NAME             STATE     TYPE        REGION      ZONE         AGE
master-machine   running   m4.xlarge   us-east-1   us-east-1a   38s
```
After an instance got provisioned:
```
NAME             STATE     TYPE        REGION      ZONE         AGE
master-machine   running   m4.xlarge   us-east-1   us-east-1a   40s
```
After a machine is requsted to be deleted:
```
NAME             STATE           TYPE        REGION      ZONE         AGE
master-machine   shutting-down   m4.xlarge   us-east-1   us-east-1a   24m
```
In order to properly display values from all the …

Set additional machine annotations/labels to get pretty machine output

---

pkg/actuators/machine/actuator.go

Fixing `/go/src/sigs.k8s.io/cluster-api-provider-aws/pkg/actuators/machine/actuator.go:467`:
```
/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/go/src/sigs.k8s.io/cluster-api-provider-aws/pkg/actuators/machine/actuator.go:467
/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go:251
/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io …
```

Do not access machine variable that is nil

---

pkg/actuators/machine/actuator.go

Master machines are created before machine manifests are. So, from pov
of the actuator, Update operation is called. Given we don't set
providerID field during update operation, all master machines have
the field unset.

Update providerID field during update operation as well

---

Makefile
hack/e2e.sh

To avoid any vendoring from cluster-api-actuator-pkg and to change ordering of tests so operator tests are ran as first to avoid loosing machine-controller logs.
Only machine-api test suite related. Has no impact on the customer. Not run in the production code.

Run machine-api directly from cluster-api-actuator-pkg@release-4.1

---

pkg/actuators/machine/actuator.go
pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/stubs.go
pkg/actuators/machine/utils.go

This attempts to mitigate https://bugzilla.redhat.com/show_bug.cgi?id=1772163.
Instead of telling the API request to filter by state tag, we fetch all and discriminate only terminated instances client side.

bug 1772163: Stop retieving instances by state tag filter on API call

---

pkg/actuators/machine/utils.go

This is not just running; see [`existingInstanceStates`][1].
[1]: https://github.com/openshift/cluster-api-provider-aws/blob/6814fc34f30a4c98d5edeb0a4ef73bbd03fa959b/pkg/actuators/machine/utils.go#L36-L46

pkg/actuators/machine/utils: Drop running/pending comment from getInstances

---

pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/awsclient_test.go
pkg/actuators/machine/instances_test.go
pkg/actuators/machine/stubs.go
pkg/actuators/machine/utils.go
pkg/client/fake/fake.go

We're already using server-side ID filtering, which means we should only ever have a single matching instance come back.  By keeping the state filtering local, we can log more interesting stuff like:
instance i-123 state terminated is not in running, pending, stopped, stopping, shutting-down
/assign @enxebre

pkg/actuators/machine/utils: Client-side state filtering in getInstanceByID and getInstances

---

pkg/actuators/machine/actuator.go

The `updateProviderID` comment was probably a copy/paste error when `setMachineCloudProviderSpecifics` landed in 716083f839 (#242).  I haven't read through the function carefully enough to be able to propose a comment that adds much beyond the function name, which is fairly clear on its own.  But I know the `updateProviderID` comment is not a good fit ;).

pkg/actuators/machine/actuator: Drop setMachineCloudProviderSpecifics comment

---

pkg/actuators/machine/actuator.go

[Avoid][1]:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-openshift-ansible-e2e-aws-scaleup-rhel7-4.3/255/artifacts/e2e-aws-scaleup-rhel7/must-gather/registry-svc-ci-openshift-org-ci-op-b24mfpd6-stable-sha256-64c63eedf863406fbc6c7515026f909a7221472cf70283708fb7010dd5e6139e/namespaces/openshift-machine-api/pods/machine-api-controllers-785b4687bf-wspnd/machine-controller/machine-controller/logs/current.log | grep -B5 'ci-op-b24mfpd6-6df53-m62pz-worker-us-east-1a-centos-sl696: found 0 existing instances for machine'
2019-11-18T01:08:14.686879882Z I1118 01:08:14.686811       1 actuator.go:552] ci-op-b24mfpd6-6df53-m62pz-worker-us-east-1a-centos-sl696: Found instance by id: i-04e60273f38857eed
2019-11-18T01:08:14.686879882Z I1118 01:08:14.686839 …
```

Bug 1761882: pkg/actuators/machine/actuator: Eventual-consistency wait for machines

---

pkg/actuators/machine/actuator.go
pkg/actuators/machine/utils.go
pkg/actuators/machine/utils_test.go

Previously we only updated the addresses in a Machine's status with
the primary public and private IP addresses and DNS names.  That
causes problems with automated CSR renewal because the Subject
Alternative Names in CSRs come from the addresses on the Node object,
which include all addresses, e.g. ones added by attaching additional
network interfaces after an instance is created.  This changes the
behavior to match what the Kubernetes AWS cloud provider does, which
is to include the addresses of all attached interfaces.

Bug 1779107: Update Machine status with all instance IP addresses

---

pkg/actuators/machine/actuator.go
pkg/actuators/machine/utils.go
pkg/actuators/machine/utils_test.go

Previously we only updated the addresses in a Machine's status with
the primary public and private IP addresses and DNS names.  That
causes problems with automated CSR renewal because the Subject
Alternative Names in CSRs come from the addresses on the Node object,
which include all addresses, e.g. ones added by attaching additional
network interfaces after an instance is created.  This changes the
behavior to match what the Kubernetes AWS cloud provider does, which
is to include the addresses of all attached interfaces.

[release-4.3] Bug 1780590: Update Machine status with all instance IP addresses

---

pkg/actuators/machine/utils.go
pkg/actuators/machine/utils_test.go

This includes any IPv6 addresses associated with an instance's network
interfaces in the Machine object's status.  They are listed with type
NodeInternalIP to match what KNI is doing:
https://github.com/openshift-kni/origin/commit/7db21c1

Include IPv6 addresses in Machine status

---

pkg/actuators/machine/actuator.go
pkg/actuators/machine/utils.go
pkg/actuators/machine/utils_test.go

Previously we only updated the addresses in a Machine's status with
the primary public and private IP addresses and DNS names.  That
causes problems with automated CSR renewal because the Subject
Alternative Names in CSRs come from the addresses on the Node object,
which include all addresses, e.g. ones added by attaching additional
network interfaces after an instance is created.  This changes the
behavior to match what the Kubernetes AWS cloud provider does, which
is to include the addresses of all attached interfaces.
Cherry-pick of:
https://github.com/openshift/cluster-api-provider-aws/pull/277
https://github.com/openshift/cluster-api-provider-aws/pull/278

[release-4.2] Bug 1781160: Update Machine status with all instance IP addresses

---

pkg/actuators/machine/actuator.go

Currently, the actual status never gets updated. First `Patch()` call updates machine, but doesn't update the status, which means that status remains outdated. The result of the first `Patch()` call is an updated machine with an outdated status. This result is saved to `machine` that we pass as an argument. When we call `Status().Patch()` later with the same machine, actual status never gets there.
The solution is to save status, before calling first `Patch()`

Bug 1796599: Save status before Patch()

---

pkg/actuators/machine/instances.go
pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go
pkg/apis/awsproviderconfig/v1beta1/zz_generated.deepcopy.go

For encyrpted EBS volumes allow users to provide ARN to the KMS keys to use. It uses the ID > ARN preference order similar to other functions
- Why only ID and ARN?
the KMS keys don't really support filtering the KMS keys based on tags. [1] & [2]
[1]: https://docs.aws.amazon.com/cli/latest/reference/kms/index.html#cli-aws-kms
[2]: https://docs.aws.amazon.com/cli/latest/reference/kms/describe-key.html

support KMS key for EBS encryption

---

pkg/actuators/machine/actuator.go
pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/utils.go
pkg/apis/awsproviderconfig/v1beta1/awsmachineproviderconfig_types.go

Refactor conditions logic and make it more simple. PR also contains a commit that removes double imports.

Refactor conditions logic

---

go.mod
go.sum
pkg/actuators/machine/actuator.go
pkg/actuators/machine/instances.go
pkg/actuators/machine/instances_test.go
pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go
vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
vendor/modules.txt

This adds `SpotMarketOptions` to the `AWSMachineProviderConfig` and then uses the values from this configuration to set the required options in the `ec2. RunInstancesInput` to launch the instances as Spot instances. This is implemented as described in https://github.com/openshift/enhancements/pull/199
Additionally it adds a label with the Instance Lifecycle to the `Machine.Spec` so that this can be propagated onto Nodes for node affinity and selection purposes. This is implemented as describe in https://github.com/openshift/enhancements/pull/251

[OCPCLOUD-801] Add support for Spot Instances in MachineProviderConfig

---

Dockerfile
Dockerfile.rhel7
Makefile
cmd/termination-handler/main.go
pkg/termination/handler.go
pkg/termination/handler_test.go
pkg/termination/termination_suite_test.go

This adds a spot termination handler to the AWS actuator image.
This binary will run on nodes and poll the AWS metadata service to check if a node has been marked for termination or not.
Based on the [spot-instances](https://github.com/openshift/enhancements/blob/master/enhancements/machine-api/spot-instances.md) proposal
This has a similar purpose to the project https://github.com/aws/aws-node-termination-handler, however differs in a number of ways:
- This version only concerns itself with spot-termination events, not scheduled maintenance
- This version does not include reporting to slack/email etc
- This version deletes Machines rather than draining them
- This leverages Machine API to handle the draining since this is already well implemented there

[OCPCLOUD-802] Add Spot terminationion notice handler

---

Dockerfile
Dockerfile.rhel7

First introduced here https://github.com/openshift/cluster-api-provider-aws/pull/12/files. I don't see a reason to keep it.

Drop openssh from the image

---

pkg/actuators/machine/actuator.go
pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/machine_scope_test.go
pkg/actuators/machine/suite_test.go

Currently, we create update events every 10 mins even if the machine is not modified. This PR should fix and create an event only if the machine is updated, that's done by comparing the resource version before and after patching machine.

Bug 1819485: Create event only if machine object was modified

---

pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go

Otherwise the value is rendered as `null` which is not a valid value for 
a boolean and causes marshalling errors
```
Invalid value: "The edited file failed validation": unknown object type "nil" in MachineSet.spec.template.spec.providerSpec.value.publicIp
```
Came across this while trying to `kubectl edit` a MachineSet
This will need the installer to bump their dependency to fix this bug

BUG 1831717: Ensure PublicIP is left out of JSON encoding if empty

---

go.mod
go.sum
vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
vendor/modules.txt

This updates the machine-api-operator dependency to include the required fix for this bug.
Will need to redo this once https://github.com/openshift/machine-api-operator/pull/599 merges to point back to the openshift fork

Bug 1840552: Update machine-api-operator dependency

---

pkg/actuators/machine/instances.go
pkg/actuators/machine/instances_test.go
pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go

This PR adds support for multiple block device mappings. The problem it solves is that machine is always created with only one disk. One of the use cases is the ability to store logs, empty dir pods data or docker images in a separate place and not have it in root one.

Add support for multiple block device mappings

---

go.sum
pkg/client/client.go

This PR adds support for custom endpoints, in order to do so we need to:
1. Fetch infrastructure object
2. Check if it contains custom endpoints in platform spec
3. Create custom endpoint resolver and use with AWS client 
https://docs.aws.amazon.com/sdk-for-go/v2/api/aws/endpoints/
https://github.com/openshift/enhancements/pull/163/files
https://github.com/openshift/installer/pull/3277/files

Add support for custom endpoints

---

pkg/termination/handler_test.go
pkg/termination/termination_suite_test.go

This PR ensures that we use an independent scheme for the test setup so that the scheme registration in the `NewHandler` method is being tested.
This also refactors the tests slightly to ensure that we don't start the handler for tests where we aren't checking it's running, because this was cause races.
Note for reviewers: This PR is best reviewed with whitespace changes turned off

Ensure we are testing scheme registration for termination handler

---

pkg/actuators/machine/instances.go
pkg/actuators/machine/instances_test.go

Currently, users can specify whatever instance tags they want
for a machineSpec.  While we attempt to remove duplicates,
this results in us removing the proper values instead of
the user supplied ones.
This commit ensures we always set the proper values
for Name and cluster tags on instances.

Bug 1866881: Filter Name/Cluster instance tags

---

OWNERS

This change adds the bugzilla component and subcomponent names to the OWNERS file to
comply with the prodsec requirements for OpenShift builds through ART.

add bugzilla component and subcomponent to OWNERS

---

pkg/actuators/machine/instances.go
pkg/actuators/machine/instances_test.go
pkg/actuators/machine/stubs.go
pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go

This PR adds support for dedicated instance tenancy.

[OCPCLOUD-960] Add support for dedicated instance tenancy

---

pkg/actuators/machine/instances.go
pkg/actuators/machine/stubs.go
pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go

Move instance tenancy under placement field.

Move instance tenancy under placement field

---

pkg/termination/handler.go
pkg/termination/handler_test.go
pkg/termination/termination_suite_test.go

Switch from deleting the Machine to marking the Node with a `Terminating` condition.
This will integrate with an MHC to ensure that the Machine is deleted.
This should be possible using the Node's credentials and as such, the termination handler will not need its own credentials and extra permissions.
Requires https://github.com/openshift/machine-api-operator/pull/627 before it will work

[OCPCLOUD-936] Bug 1902157: Mark node with condition when due for termination

---

go.sum
pkg/client/client.go

@joelddiaz @abhinavdahiya @michaelgugino @JoelSpeed 
In order to support various styles of authentication, mostly STSAsumeRoleUsingWebhookIdentity, the operator should support using the AWS SDK's default handling of the shared credential file.
Previously the operator only supported static credentials from specific keys in the AWS secret, but now the operator supports reading credentials key to load the shared credential file and pass it on as-is to AWS SDK to authenticate based on the contents of that file.
To make the code easier, the operator now converts the previous access_key, secret_key case into a shared credential file using those values and then using that like if it was provided.
https://issues.redhat.com/browse/CO-1275

use shared credentials file for session creation

---

pkg/client/client.go
pkg/client/client_test.go

When a cluster is installed in a AWS C2S region, access to the AWS API requires a custom CA bundle for trust. The custom CA bundle is read from the "ca-bundle.pem" key of the kube-cloud-config ConfigMap in the openshift-config-managed namespace.
https://issues.redhat.com/browse/CORS-1584

support custom CA bundle for AWS API

---

pkg/actuators/machine/reconciler.go

To enable the termination handler MHC to work, we need to label the Machine as well as the Node as interruptible.

Bug 1907286: Ensure Machine is marked interruptible as well as Node

---

cmd/manager/main.go
pkg/client/client.go

This PR ensures that any time we create a client, if the endpoint doesn't resolve to a known standard or custom endpoint, the error returned is an AWS `endpoints.UknownEndpointError` instead of a request error.
Currently, the endpoint resolver falls back to constructing an invalid URL when it doesn't know a particular region, this results in request being made and the error returning looking like `Request Error: Unable to resolve host:...`, now the error will correctly be wrapped such that is says `region "foo" not resolved: Unknown Endpoint: ...` which should hopefully narrow down that the issue is a user input error faster.
This doesn't fully resolve the attached bug but will improve the error message to help towards a resolution.

Bug 1906740: Ensure the region is valid when creating AWS client

---

cmd/manager/main.go
pkg/actuators/machine/actuator.go
pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/machine_scope.go
pkg/actuators/machine/machine_scope_test.go
pkg/actuators/machine/reconciler_test.go
pkg/client/client.go

The controller-runtime client that is create with the manager only has access to objects in the openshift-machine-api namespace. Consequently, attempts to fetch the kube-cloud-config ConfigMap from the openshift-config-managed namespace using that client return NotFound. These changes create a new, additional client limited to the openshift-config-managed namespace and plumb the new client through to where it is needed for fetching the custom CA bundle.

Bug 1915114: use separate client for accessing openshift-config-managed namespace

---

pkg/termination/handler.go

When creating an http request in go, this sets two goroutines in the background running. If the body is not closed properly, these goroutines are leaked. This leads to a gradual increase in memory used by the application over time. We must ensure we always close response bodies

Bug 1934021: Ensure response body is closed when we are finished with the request

---

pkg/actuators/machine/instances_test.go
pkg/actuators/machine/loadbalancers.go
pkg/actuators/machine/loadbalancers_test.go
pkg/actuators/machine/reconciler.go
pkg/actuators/machine/stubs.go
pkg/client/client.go
pkg/client/fake/fake.go
pkg/client/mock/client_generated.go

Installer should register LB groups by instance id. We still need to handle removal of ip target group attachments for older clusters.

Bug 1880757: Unset target groups from LB on deletion

---

Makefile

this change ensure that running the unit test inside of container will
work properly with the CGO_ENABLED setting.

Bug 1948719: update makefile to ensure that CGO_ENABLE is set properly

---

pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/instances.go
pkg/actuators/machine/instances_test.go
pkg/actuators/machine/reconciler.go
pkg/actuators/machine/reconciler_test.go
pkg/actuators/machine/suite_test.go
pkg/client/client.go

Get instance tags from infrastructure objects. Tags that come from the infra object have precedence over providerSpec.
Related enhancements: https://github.com/openshift/enhancements/pull/706

Bug 1952611: [OCPCLOUD-1115] Get instance tags from infrastructure object

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/controller-runtime/Makefile
vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/metadata_infomer_wrapper.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/selector.go
vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/client_cache.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/metadata_client.go
vendor/sigs.k8s.io/controller-runtime/pkg/client/namespaced_client.go
vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go
vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/multi.go
vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics/metrics.go
vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go

this update is to bring the controller-runtime dependency past the alpha
version into the current beta release. this is being done to pickup
several changes that happened between the alpha and beta release,
amongst them is the switch from using k8s v0.21.0-beta.1 to v.0.21.0.

Bug 1948719: update controller-runtime dependency

---

Makefile
hack/go-mod.sh

Add option to run make vendor in container like other targets, to avoid issues with go module caching depending on what you already have on your machine.

add in-container vendor

---

pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/instances_test.go
pkg/actuators/machine/loadbalancers.go
pkg/actuators/machine/loadbalancers_test.go
pkg/actuators/machine/reconciler_test.go
pkg/actuators/machine/stubs.go
pkg/client/client.go
pkg/client/fake/fake.go
pkg/client/mock/client_generated.go

This PR changes the load balancer registration logic so that we only actually register targets if and when they need registering, rather than constantly registering them whenever the machine is reconciled.
When using write operations, this tends to be more expensive for an API, if we can prevent write operations by using a read first, we are in the most case, being a better consumer of the API.
In the case of this bug, we are seeing frequent requests to an API which doesn't have the correct permissions, because this is an inferred permission, this should reduce this kind of problem in the future.

Bug 1965080: Reduce frequency of calls to register targets with load balancers

---

pkg/actuators/machine/reconciler.go
pkg/actuators/machine/reconciler_test.go
pkg/actuators/machine/stubs.go

Based on:  https://github.com/openshift/cluster-api-provider-aws/pull/384
> Eventual consistency logic is not aligned with
> MAO after phases were added. This is causing
> some machines to go failed when they shouldn't.
> 
> This commit also removes the error after create
> as it is no longer useful. We manipulate the
> machine-object and status, so the next request
> will be requeued and our delay attempt is ignored.
>

Bug 1925276:  Fix eventual consistency logic to be consistent 

---

pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/reconciler.go
pkg/actuators/machine/reconciler_test.go
pkg/actuators/machine/stubs.go

Cherry-pick of https://github.com/openshift/cluster-api-provider-aws/pull/406

[release-4.8] Bug 1974680: Fix eventual consistency logic to be consistent

---

Dockerfile
Makefile
go.mod

This commit sets the minimal golang version for the project to 1.16.

Upgrade to use golang 1.16

---

pkg/actuators/machine/reconciler.go

Commit https://github.com/openshift/cluster-api-provider-aws/commit/85f17532d0d9ef0d603c85e0e45acefc3a89a788 accidentally removed the check to ensure that the machine hasn't been updated before requeueing. It causes a problem with situations when the machine's vm has been removed, but the machine object's still available.
In this case starts requeueing the machine in an infinite loop, preventing it to be deleted or updated.
To fix it, this commit returns the additional checks.

Bug 2007802: do not requeue if the machine has been updated

---

pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/controller_test.go
pkg/actuators/machine/machine_scope.go
pkg/actuators/machine/reconciler.go
pkg/actuators/machine/reconciler_test.go
pkg/actuators/machine/stubs.go
pkg/actuators/machine/suite_test.go

We are seeing instances where AWS is not returning the instance we just created within a second or two of the initial creation time, returning a 400 error saying that the instance does not exist.
This makes the machine go into failed right now, and, in conjunction with an MHC, can lead to leaked machines as the instances are deleted before AWS acknowledges the existence of the Machine.
This PR is an attempt to improve this experience.
It does:
Do not set the addresses after create - this prevents the machine controller from saying the instance is provisioned, if exists does not return the instance, it will call create again
Before we create, we attempt exists again by looking for existing instances - if this succeeds, requeue and the next reconcile should work and call Update which …

Bug 2029993: Prevent Machine from being considered provisioned until it exists in AWS

---

pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/controller_test.go
pkg/actuators/machine/machine_scope.go
pkg/actuators/machine/reconciler.go
pkg/actuators/machine/reconciler_test.go
pkg/actuators/machine/stubs.go
pkg/actuators/machine/suite_test.go

We are seeing instances where AWS is not returning the instance we just created within a second or two of the initial creation time, returning a 400 error saying that the instance does not exist.
This makes the machine go into failed right now, and, in conjunction with an MHC, can lead to leaked machines as the instances are deleted before AWS acknowledges the existence of the Machine.
This PR is an attempt to improve this experience.
It does:
Do not set the addresses after create - this prevents the machine controller from saying the instance is provisioned, if exists does not return the instance, it will call create again
Before we create, we attempt exists again by looking for existing instances - if this succeeds, requeue and the next reconcile should work and call Update which …

Bug 2031905: Prevent Machine from being considered provisioned until it exists in AWS

---

.gitignore
vendor/sigs.k8s.io/cluster-api/util/kubeconfig/kubeconfig.go
vendor/sigs.k8s.io/cluster-api/util/kubeconfig/testing.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/encode.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/helpers.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/lock.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/merge.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/paths.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/read.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/remove.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/types.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/write.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/kubeconfig.go

.gitignore excludes kubeconfig from vendor and breaks CI builds. I will put a patch upstream to have it included in next rebase.

UPSTREAM: <carry>: Don't ignore kubeconfig package in vendor

---

pkg/actuators/machine/instances.go

This is a cherry-pick of https://github.com/openshift/machine-api-provider-aws/pull/18
AWS documentation suggests that IO1, IO2 and GP3 block devices all support a configurable IOPS setting. We are only allowing this for IO1 right now, so we should make sure that we set the IOPS on other supported types as well.
> The following are the supported values for each volume type:
> 
> gp3 : 3,000-16,000 IOPS
> io1 : 100-64,000 IOPS
> io2 : 100-64,000 IOPS

Bug 2065483: Ensure IOPS setting is honoured on all supported block device types

---

pkg/actuators/machine/actuator.go
pkg/actuators/machine/actuator_test.go
pkg/actuators/machine/controller_test.go
pkg/actuators/machine/machine_scope.go
pkg/actuators/machine/machine_scope_test.go
pkg/actuators/machine/reconciler_test.go
pkg/client/client.go
pkg/client/mock/client_generated.go

Manual backport of https://github.com/openshift/machine-api-provider-aws/pull/48 because this branch is in different repo.
https://github.com/openshift/machine-api-operator/pull/1048 needs to merge as well.

[release-4.9] Bug 2111004: Validate unknown regions using AWS API

---

pkg/actuators/machine/reconciler.go

Manual backport of https://github.com/openshift/machine-api-provider-aws/pull/50 because this branch is in different repository.

OCPBUGS-572: Fix panic when accessing nil machine annotations map

---

go.mod
vendor/modules.txt

Specify 'concrete' version of
sigs.k8s.io/cluster-api-provider-{aws|azure}
which makes go to make a correct replace in
`modules.txt` file.

OCPBUGS-2578: Fix go list for go1.18

---

go.mod
vendor/modules.txt

Specify 'concrete' version of
sigs.k8s.io/cluster-api-provider-{aws|azure}
which makes go to make a correct replace in
`modules.txt` file.

OCPBUGS-2861: Release-4.8 Fix go list for go1.18

---

go.mod
go.sum
vendor/modules.txt

Specify 'concrete' version of
sigs.k8s.io/cluster-api-provider-{aws|azure}
which makes go to make a correct replace in
`modules.txt` file.

OCPBUGS-2862: Release 4.7 fix go list for 1.18

---

openshift/e2e-tests.sh

This PR adds a script under `openshift/e2e-tests.sh` which can be invoked manually or through the OpenShift CI steps (as we already do for [unit tests](https://github.com/openshift/release/blob/ecf68889eb6507167b2a90d8daa95061b430efe2/ci-operator/config/openshift/cluster-api-provider-gcp/openshift-cluster-api-provider-gcp-master.yaml#LL44C1-L47C14)) to launch CAPI E2E tests from within the provider repo.
This mimics the [approach in the MAPI providers]( https://github.com/openshift/machine-api-provider-aws/blob/425a29de158582a931fd8052b306f4589ee90b61/hack/e2e.sh#L1C1-L10) where we clone the repo where the e2e tests reside and launch those from within the provider repo PRs.

OCPCLOUD-2121: Add openshift/e2e-tests for CAPI E2E testing

---

pkg/cloud/services/ec2/instances.go

When IsExternallyManaged we want to make sure additionalSecurityGroups are passed on creation to satisfy user intent. This also prevents the default VPC SG from silently attached to the ec2 and so deviating even more from user intent.

OCPBUGS-14969: Pass right SGs for IsExternallyManaged on creation

---

openshift/e2e-tests.sh

Fix e2e tests on release branches by running cluster-capi-operator tests off of the matching release branch.

OCPBUGS-30586: fix e2e tests on release branches

---

pkg/cloud/services/ec2/instances.go

Carrying  [4670](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4670)

[release-4.15] OCPBUGS-31036: UPSTREAM: 4670:Update awsmachine providerID and instanceID immediately after ec2:RunInstances is called

---

cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
controllers/awsmachine_controller_test.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go

Initial Bugfix [OCPBUGS-29391](https://issues.redhat.com/browse/OCPBUGS-29391)
When a VPC sets a DHCPOption's domain-name with a custom DNS name, it's being ignored. Now, with this PR, ensure that during instance creation, the controller checks the DHCPOptions and sets the proper PrivateDNSName.

OCPBUGS-32114: UPSTREAM: <carry>: Fix instance PrivateDNSName when domain-name is set in dhcpOpts

---

pkg/cloud/services/ec2/instances.go

[release-4.13] OCPBUGS-32470: UPSTREAM: 4670:Update awsmachine providerID and instanceID immediately after ec2:RunInstances is called

---

openshift/manifests/0000_30_cluster-api_04_cm.infrastructure-aws.yaml
openshift/tools/go.mod
openshift/tools/go.sum
openshift/tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen/customizations.go
openshift/tools/vendor/modules.txt

In 4.17, we are enforcing this value for all OpenShift containers via tests, link in bug comment. This helps with debugging to ensure we have logs available.
Ref: https://github.com/openshift/cluster-capi-operator/pull/172

OCPBUGS-33170: All containers must fallback to logs on error

---

.ci-operator.yaml
openshift/Dockerfile.openshift

Reconciling with https://github.com/openshift/ocp-build-data/tree/4c1326094222f9209876f06833179a1b9178faf7/images/ose-aws-cluster-api-controllers.yml

OCPBUGS-34382: Updating ose-aws-cluster-api-controllers-container image to be consistent with ART for 4.17

---

controllers/awsmachine_controller_test.go
pkg/cloud/awserrors/errors_patch.go
pkg/cloud/services/ec2/bastion_test.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_patch.go
pkg/cloud/services/ec2/instances_patch_test.go
pkg/cloud/services/ec2/instances_test.go

This is a manual cherry-pick of the following commits onto the `release-4.16` branch, as I had to resolve conflicts with both.
[5c786778e66b9081de238480b18c6db9d420bd3b](https://github.com/openshift/cluster-api-provider-aws/commit/5c786778e66b9081de238480b18c6db9d420bd3b)
[7d4d4b779f65bd40891faa157fe2ab54047b86c6](https://github.com/openshift/cluster-api-provider-aws/commit/7d4d4b779f65bd40891faa157fe2ab54047b86c6)

OCPBUGS-44234: [release-4.16] OSD-25934: Only tag NetworkInterfaces in RunInstances if IAM Allows It

---

controllers/awsmachine_controller_test.go
pkg/cloud/awserrors/errors_patch.go
pkg/cloud/services/ec2/bastion_test.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_patch.go
pkg/cloud/services/ec2/instances_patch_test.go
pkg/cloud/services/ec2/instances_test.go

This is a manual cherry-pick of the following commits onto the release-4.15 branch, as I had to resolve conflicts with both. There are significant changes to behaviors, mostly around this older branch not using updated AWS SDK calls `WithContext()`.
[5c786778e66b9081de238480b18c6db9d420bd3b](https://github.com/openshift/cluster-api-provider-aws/commit/5c786778e66b9081de238480b18c6db9d420bd3b)
[7d4d4b779f65bd40891faa157fe2ab54047b86c6](https://github.com/openshift/cluster-api-provider-aws/commit/7d4d4b779f65bd40891faa157fe2ab54047b86c6)

OCPBUGS-44294: [release-4.15] OSD-25934: Only tag NetworkInterfaces in RunInstances if IAM Allows It

---

controllers/awsmachine_controller_test.go
pkg/cloud/awserrors/errors_patch.go
pkg/cloud/services/ec2/bastion_test.go
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_patch.go
pkg/cloud/services/ec2/instances_patch_test.go
pkg/cloud/services/ec2/instances_test.go

This is a manual cherry-pick of the following commits onto the release-4.14 branch, as I had to resolve conflicts with both. There are significant changes to behaviors, mostly around this older branch not using updated AWS SDK calls WithContext().
[5c786778e66b9081de238480b18c6db9d420bd3b](https://github.com/openshift/cluster-api-provider-aws/commit/5c786778e66b9081de238480b18c6db9d420bd3b)
[7d4d4b779f65bd40891faa157fe2ab54047b86c6](https://github.com/openshift/cluster-api-provider-aws/commit/7d4d4b779f65bd40891faa157fe2ab54047b86c6)

OCPBUGS-44295: [release-4.14] OSD-25934: Only tag NetworkInterfaces in RunInstances if IAM Allows It

---

.gitignore
vendor/github.com/sagikazarmark/locafero/.envrc
vendor/github.com/sagikazarmark/slog-shim/.envrc
vendor/github.com/spf13/viper/.envrc
vendor/github.com/subosito/gotenv/.env

Image build was failing on Konflux due to missing go mod dependencies.
```
2025-04-04 17:30:46,824 ERROR vendor directory changed after vendoring:
A	vendor/github.com/sagikazarmark/locafero/.envrc
A	vendor/github.com/sagikazarmark/slog-shim/.envrc
A	vendor/github.com/spf13/viper/.envrc
A	vendor/github.com/subosito/gotenv/.env
```
Konflux ignores .gitignore files since its a possible security gap.

ART-12521: update go mod dependency for konflux

---

api/v1beta2/awsmachine_types.go
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
exp/api/v1beta2/awsmachinepool_webhook.go
exp/api/v1beta2/awsmachinepool_webhook_test.go
openshift/infrastructure-components-openshift.yaml
openshift/manifests/0000_30_cluster-api_04_cm.infrastructure-aws.yaml
pkg/cloud/services/ec2/instances.go
pkg/cloud/services/ec2/instances_test.go

- If only MarketType=Spot is specified but spotMarketType is not provided, then we must explicitly add spotMarketType to the API configuration.
- Webhook validation for the marketType field value
Ref: [https://issues.redhat.com/browse/OCPBUGS-54567](https://issues.redhat.com/browse/OCPBUGS-54567)

OCPBUGS-54567: UPSTREAM: 5374: add marketType field validation

---

openshift/e2e-tests.sh

This is to support renaming the master branch to main.
Counterpart to openshift/release#62705
/hold
Hold for CRT to coordinate merging of all relevant PRs.

OCPBUGS-53003: Remove references to master branch

---

go.mod
go.sum
vendor/github.com/golang/glog/glog.go
vendor/modules.txt

bump github.com/golang/glog to v1.2.5

[release-4.19] OCPBUGS-59241,OCPBUGS-59242: bump github.com/golang/glog to v1.2.5

---

go.mod
go.sum
vendor/github.com/golang/glog/glog.go
vendor/github.com/golang/glog/glog_file.go
vendor/github.com/golang/glog/glog_file_nonwindows.go
vendor/github.com/golang/glog/glog_file_windows.go
vendor/modules.txt

bump github.com/golang/glog to v1.2.5

[release-4.18] OCPBUGS-58675,OCPBUGS-58670: bump github.com/golang/glog to v1.2.5

---

go.mod
go.sum
vendor/github.com/golang/glog/glog.go
vendor/modules.txt

bump github.com/golang/glog to v1.2.5

[release-4.17] OCPBUGS-58669,OCPBUGS-58674: bump github.com/golang/glog to v1.2.5
