- cmd/aws-actuator/README.md
- examples/master-machine.yaml
- examples/master-user-data.sh
- examples/master-userdata.yaml
- examples/worker-machine.yaml
- examples/worker-user-data.sh
- examples/worker-userdata.yaml
Just to demonstrate how to bootstrap a simple kubernetes cluster with the aws actuator.
Fixes: https://github.com/openshift/cluster-api-provider-aws/issues/9
> Bootstrap kubernetes cluster with kubeadm examples

- OWNERS
Change code ownership so Prow can do it's job.
> Assign downstream code ownership for CI

- test/utils/utils.go
> Push missing test/utils

- cloud/aws/actuators/machine/actuator.go
Errors returned to the controller do not seem to automatically be
logged. Added logging where necessary to make sure we stop swallowing
errors silently.
Fixes: https://github.com/openshift/cluster-api-provider-aws/issues/17
> Add explicit error logging in actuator.

- examples/machine-set.yaml
- examples/machine.yaml
- examples/worker-machine.yaml
> Make all examples use ami-060f14ef82deddfc6

- cloud/aws/actuators/machine/actuator.go
- examples/machine-set.yaml
- examples/machine-with-user-data.yaml
- examples/machine.yaml
- examples/master-machine.yaml
- examples/worker-machine.yaml
Fixes: https://github.com/openshift/cluster-api-provider-aws/issues/3
> Lookup for AMI using filters

- cloud/aws/providerconfig/register.go
- cloud/aws/providerconfig/v1alpha1/register.go
- clusterctl/examples/aws/cluster.yaml.template
- examples/machine-set.yaml
- examples/machine-with-user-data.yaml
- examples/machine.yaml
- examples/master-machine.yaml
- examples/worker-machine.yaml
Fixes: https://github.com/openshift/cluster-api-provider-aws/issues/18
> Change apiVersion from awsproviderconfig to aws.cluster.k8s.io.

- Dockerfile
- examples/provider-components.yml
Will allow for keeping versions in sync.
> Bundle controller manager into the AWS machine controller image.

- Makefile
- cloud/aws/actuators/machine/actuator.go
- cloud/aws/actuators/machine/actuator_test.go
- cloud/aws/actuators/machine/utils.go
- cloud/aws/client/client.go
- cloud/aws/controllers/cluster/controller.go
- cloud/aws/controllers/cluster/options/options.go
- cloud/aws/controllers/machine/controller.go
- cloud/aws/controllers/machine/options/options.go
- cloud/aws/providerconfig/register.go
- cloud/aws/providerconfig/types.go
- cloud/aws/providerconfig/v1alpha1/register.go
- cloud/aws/providerconfig/v1alpha1/types.go
- cmd/aws-actuator/main.go
- cmd/machine-controller/main.go
- test/integration/create_update_delete_test.go
- test/utils/utils.go
> Address make vet/fmt complaints

- Makefile
- cloud/aws/actuators/machine/actuator.go
- cmd/aws-actuator/README.md
- cmd/aws-actuator/main.go
- examples/machine-with-user-data.yaml
- examples/master-machine.yaml
- examples/worker-machine.yaml
- hack/aws-provision.sh
- hack/prebuild/main.tf
- hack/prebuild/security_groups.tf
- hack/prebuild/variables.tf
- test/infra.tf
- test/variables.tf
This is needed as part of standing up a cluster for the cluster autoscaler & machine API integration work.
> Provider terraform and update examples to use filters

- cloud/aws/actuators/machine/actuator.go
- cmd/aws-actuator/README.md
- cmd/aws-actuator/main.go
- examples/provider-components.yml
Just run it and get the cluster API stack in k8s running in AWS.
```sh
$ cd hack
$ ENVIRONMENT_ID=UNIQUE_ID ./aws-provision.sh install
$ cd ..
$ ./bin/aws-actuator bootstrap --manifests examples --environment-id UNIQUE_ID --cluster-api-stack
```
> Bootstrap cluster API stack

- examples/worker-machineset.yaml
> Propagate node role through machine spec label

- cloud/aws/actuators/machine/actuator.go
- cmd/aws-actuator/main.go
> Make golint happy

- OWNERS
> Add more owners

- Makefile
- hack/go-fmt.sh
- hack/go-lint.sh
- hack/go-vet.sh
- Create same image as CI
- unify Makefile across all our repos
- better `hack/go-*` scripts (easier to copy-paste to new repos)
> tooling unification

- pkg/cloud/aws/actuators/machine/actuator.go
- pkg/cloud/aws/actuators/machine/actuator_test.go
add unit test for buildEC2Filters
> add unit test for buildEC2Filters

- pkg/cloud/aws/actuators/machine/actuator.go
If existing and updated ProviderStatus are compared using `equality.Semantic.DeepEqual()` in encoded formats(raw form), `DeepEqual()` always returns False whether the two are equal or not. However if compared in decoded form `DeepEquall()`  return correct result. 
MachineStatus keeps providerStatus in encoded format and therefore when existing and updated machineStatus are compared in DeepEqual(), always found to be unequal. To fix this, PR is comparing ProviderStatus in decoded format and updating MachineStatus if found unequal.
>  Stop nonstop status reconciliation

- cmd/manager/main.go
- examples/provider-components.yml
- vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go
SSIA
/hold
/assign @ingvagabund
> remove log-level option

- cmd/aws-actuator/main.go
- Use `err` in log messages
- get `machine` directly from `readMachineManifest()`
> make ineffectual assignment effective

- Gopkg.lock
- vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
- vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/clusterapi.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machines.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
Vendored PR: https://github.com/openshift/cluster-api-actuator-pkg/pull/21
> Revendor deps to deploy manager controller with machine controller

- Makefile
- test/e2e/main.go
- test/e2e/provider_expectations.go
Reuse test suite from mao to provide e2e gating tests for AWS provider.
> e2e gating

- pkg/apis/awsproviderconfig/v1alpha1/register.go
- pkg/cloud/aws/actuators/machine/actuator.go
- pkg/cloud/aws/actuators/machine/actuator_test.go
- pkg/cloud/aws/actuators/machine/utils.go
- pkg/cloud/aws/actuators/machine/utils_test.go
- test/machines/utils.go
All coding/decoding algorithms of machine types should be at a single place/package.
> Turn coding/decoding functions into codec methods

- pkg/apis/awsproviderconfig/v1alpha1/awsmachineproviderconfig_types.go
Add +optional declarative to optional fields.
Add omitempty for optional fields.
> Fix optional fields and omitempty

- pkg/actuators/machine/instaces_test.go
> Verify launchInstance failed/succeeded properly

- pkg/actuators/machine/awsclient.go
- pkg/actuators/machine/utils.go
- pkg/client/client.go
- pkg/client/fake/fake.go
- pkg/client/mock/client_generated.go
- test/machines/machines_test.go
- test/utils/manifests.go
Adds e2e tests for EBS support.
> Add e2e tests for EBS support

- test/e2e/main.go
For reference:
https://github.com/openshift/installer/pull/1215
> Update namespace -> openshift-machine-api

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
Sync deps by running `dep ensure`
> Add more RBAC rules to properly drain

- pkg/actuators/machine/actuator.go
If a machine is not linked to a node, just delete the machine. Since a node
can be unlinked from a machine when the node goes NotReady and is removed
by cloud controller manager. In that case some machines would never get
deleted without a manual intervention.
> Allow to delete machine not linked to any node

- Gopkg.lock
- vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
- vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/common.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/framework.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machinehealthcheck.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/machines.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/nodes.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/infra.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/utils.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/machinehealthcheck/machinehealthcheck.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/machine-api-operator.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go
- vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
Bumping cluster-api-actuator-pkg deps for:
- openshift/cluster-api-actuator-pkg#61
- openshift/cluster-api-actuator-pkg#63
> bump cluster-api-actuator-pkg

- OWNERS
SSIA
/assign @enxebre @ingvagabund
> Remove myself from OWNERS file

- pkg/actuators/machine/actuator.go
If the actuator is unable to detemine if a machine is master,
just skip deleting any stopped machines. Most likely caused
by a missing instance. Or, by missing node object.
Bug#1697278
> Skip deletion of stop machines if there is an error

- pkg/actuators/machine/filter.go
- pkg/actuators/machine/instances.go
- pkg/actuators/machine/utils.go
- test/machines/machines_test.go
> Remove clusterid tag

- Gopkg.lock
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
- vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
- vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
By running "dep ensure -v -update github.com/openshift/cluster-api".
Picking https://github.com/openshift/cluster-api/pull/26
> Sync with the latest openshift/cluster-api

- Gopkg.lock
- vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock
- vendor/github.com/openshift/cluster-api-actuator-pkg/Makefile
- vendor/github.com/openshift/cluster-api-actuator-pkg/hack/ci-integration.sh
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
- vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
- vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
- vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
dep ensure -v -update github.com/openshift/cluster-api-actuator-pkg
dep ensure -v -update github.com/openshift/cluster-api
https://bugzilla.redhat.com/show_bug.cgi?id=1701450
> Sync with the latest cluster-api and cluster-api-actuator-pkg

- pkg/actuators/machine/actuator.go
- pkg/actuators/machine/actuator_test.go
- pkg/actuators/machine/stubs.go
https://jira.coreos.com/browse/CLOUD-445
> Update machine.Spec.ProviderID field

- pkg/actuators/machine/actuator.go
> Check if placement is not nil before accessing AvailabilityZone field

- pkg/actuators/machine/actuator.go
This will allow users to more easily utilize grep
when troubleshooting a problematic machine.
> Prepend machine.Name to all logging

- Makefile
- hack/goimports.sh
- pkg/client/mock/client_generated.go
So the target can be run in CI and fail in case files are not properly goimport formated.
> Add goimports into makefile

- Makefile
- pkg/apis/awsproviderconfig/v1beta1/zz_generated.deepcopy.go
- pkg/client/mock/client_generated.go
> Apply 'make goimports' changes

- pkg/actuators/machine/actuator_test.go
Add unit test coverage for actuator.create
> Add unit test coverage for actuator.create

- pkg/actuators/machine/actuator.go
Same guard `Update` grew in 09c1fe9cee9e68 (#271), but now for `Exists` and `Describe`.  This should protect us from flows [like][1]:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/2712/pull-ci-openshift-installer-master-e2e-aws-scaleup-rhel7/3059/artifacts/e2e-aws-scaleup-rhel7/must-gather/registry-svc-ci-openshift-org-ci-op-nr00dj4c-stable-sha256-b6dffb34bfe5c198d7e9ad032322277c2a129e45a4e7f2084a83ab560530f683/namespaces/openshift-machine-api/pods/machine-api-controllers-9bd7457fc-tfdmg/machine-controller/machine-controller/logs/current.log | grep ci-op-nr00dj4c-9de00-ls2x8-worker-us-east-1a-rhel-fdknz
...
2019-11-22T17:39:34.642709291Z I1122 17:39:34.642651       1 actuator.go:194] …
```
> Bug 1761882: pkg/actuators/machine: Eventual-consistency guards for Exists/Describe

- pkg/actuators/machineset/controller.go
And invalid instanceType wouldn't ever succeed, therefore no point on requeuing.
Addresses https://github.com/openshift/cluster-api-provider-aws/pull/301#discussion_r391055028
> Don't return error with invalid instance type in machineSet annotations reconciler.

- go.mod
- hack/go-fmt.sh
- hack/go-lint.sh
- hack/go-vet.sh
- hack/goimports.sh
This bumps all remaining scripts to Go 1.13
> [OCPCLOUD-813] Bump scripts to Go 1.13

- cmd/manager/main.go
Implemented leader election for aws manager
> [OCPCLOUD-492]; Run all machine api Controllers using leader election

- go.mod
- go.sum
- vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
- vendor/modules.txt
Revendor MAO with timeout formatting fix
> [release-4.4] Bug 1810531: Revendor MAO with timeout formatting fix

- Dockerfile
- Makefile
- go.mod
- go.sum
- hack/go-fmt.sh
- hack/go-lint.sh
- hack/go-vet.sh
- hack/goimports.sh
- vendor/modules.txt
Unblocks https://github.com/openshift/release/pull/13785
> [OCPCLOUD-977] Bump scripts to Go 1.15

- Makefile
- README.md
- hack/go-fmt.sh
- hack/go-lint.sh
- hack/go-vet.sh
- hack/goimports.sh
- hack/imagebuilder.sh
- hack/owner_reset.sh
- hack/verify-actuator-pkg.sh
- pkg/actuators/machine/machine_scope_test.go
- pkg/actuators/machine/stubs.go
Fixed broken Makefile targets.
Added script to fix permission issues.
Added [openshift/imagebuilder](https://github.com/openshift/imagebuilder) package to vendor.
Updated Readme.
> [OCPCLOUD-1066] Makefile fix 

- pkg/actuators/machineset/controller_test.go
- pkg/actuators/machineset/ec2_instance_types.go
> Update EC2 instance types

- pkg/actuators/machineset/controller.go
- pkg/actuators/machineset/controller_test.go
Prevent endless reconciles for machineSet due to failed attempt to set scale from zero annotation when the instance type is missing in our static list.
> Bug 1918910: Only log error on wrong instance type for scale from zero

- metadata.yaml
Includes fix merged upstream in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4386
> Fix version in metadata.yaml

- .snyk
Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!
> OCPBUGS-26181: Add Snyk file to exclude vendor directory on scan

- .snyk
Hello! This is a PR to update the existing snyk file to exclude things we don't want included in the regular scans. Thanks!
> OCPBUGS-27871: Update snyk exclusion file

- go.mod
- go.sum
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/golang/glog/glog_file.go
- vendor/github.com/golang/glog/glog_file_nonwindows.go
- vendor/github.com/golang/glog/glog_file_windows.go
- vendor/modules.txt
> OCPBUGS-49400: UPSTREAM: 5339: Bump glog for recent fixes

- go.mod
- go.sum
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/golang/glog/glog_file.go
- vendor/github.com/golang/glog/glog_file_nonwindows.go
- vendor/github.com/golang/glog/glog_file_windows.go
- vendor/modules.txt
bump github.com/golang/glog to v1.2.5
> [release-4.16] OCPBUGS-58666,OCPBUGS-58671: bump github.com/golang/glog to v1.2.5
